Don't fail in the init script when we cannot raise the ulimit. Instead just warn a bit (closes: #312882).
svn:r4398

diff --git a/branches/tor-0_1_0-patches/debian/tor.init b/branches/tor-0_1_0-patches/debian/tor.init
--- a/branches/tor-0_1_0-patches/debian/tor.init
+++ b/branches/tor-0_1_0-patches/debian/tor.init
@@ -51,7 +51,7 @@ case "$1" in
 		echo "Not starting $DESC (Disabled in $DEFAULTSFILE)."
 	else
 		echo "Starting $DESC: $NAME..."
-		ulimit -n $MAX_FILEDESCRIPTORS
+		ulimit -n $MAX_FILEDESCRIPTORS || echo "Warn: Could not set ulimit for number of file descriptors." >&2
 		start-stop-daemon --start --quiet --oknodo \
 			--chuid debian-tor:debian-tor \
 			--pidfile $TORPID \
