Only create pid dir if we are about to start Tor (Luca Capello, closes: #447508)
svn:r12085

diff --git a/debian/tor.init b/debian/tor.init
--- a/debian/tor.init
+++ b/debian/tor.init
@@ -61,16 +61,18 @@ wait_for_deaddaemon () {
 }
 
 
-if test ! -d $TORPIDDIR; then
-	echo "There is no $TORPIDDIR directory.  Creating one for you."
-	mkdir -m 02700 "$TORPIDDIR"
-	chown debian-tor:debian-tor "$TORPIDDIR"
-fi
+check_torpiddir () {
+	if test ! -d $TORPIDDIR; then
+		echo "There is no $TORPIDDIR directory.  Creating one for you."
+		mkdir -m 02700 "$TORPIDDIR"
+		chown debian-tor:debian-tor "$TORPIDDIR"
+	fi
 
-if test ! -x $TORPIDDIR; then
-	echo "Cannot access $TORPIDDIR directory, are you root?" >&2
-	exit 1
-fi
+	if test ! -x $TORPIDDIR; then
+		echo "Cannot access $TORPIDDIR directory, are you root?" >&2
+		exit 1
+	fi
+}
 
 
 case "$1" in
@@ -88,6 +90,8 @@ case "$1" in
 			echo ": FAILED."
 		fi
 	fi
+
+	check_torpiddir
 
 	echo "Starting $DESC: $NAME..."
 	if ! su -s /bin/sh -c "$DAEMON --verify-config" debian-tor > /dev/null; then
